### PR TITLE
dev_1374: Override for `monaca plugin add|rm|remove`

### PR DESCRIPTION
**Pull request by magyarbitware**
I created this overrides based on the Import plugin feature in the Cloud IDE.
I also added some unit tests as at the end it become hard to test all the edge cases.
They also show what cases the command overrides cover.
Please make any suggestions for further improvements.
Thank you.

### CODE REVIEW

**Comment by magyarbitware** [comment]
Commands that I have tested with are:
Add plugin from npm:
`monaca plugin add cordova-plugin-camera`

Add from file:
`monaca plugin add file:/c:\\temp\\cordova-plugin-camera`
`monaca plugin add file://c:\\temp\\cordova-plugin-camera`
`monaca plugin add file:///c:\\temp\\cordova-plugin-camera`

Add from URL: (only GitHub and Gitlab is supported)
`monaca plugin add https://github.com/apache/cordova-plugin-camera/`
`monaca plugin add https://github.com/apache/cordova-plugin-camera#2.2.x`
`monaca plugin add https://github.com/apache/cordova-plugin-camera.git#4.1.0`

`monaca plugin add https://gitlab.com/creare-com/cordova-plugin-creare-tabsintreceiver`
`monaca plugin add https://gitlab.com/creare-com/cordova-plugin-creare-tabsintreceiver#cc0a604d643107f426ae35276fbe7dfaac435105`
`monaca plugin add https://gitlab.com/creare-com/cordova-plugin-creare-tabsintreceiver.git#cc0a604d643107f426ae35276fbe7dfaac43510`

Remove plugin:
`monaca plugin remove cordova-plugin-camera`
`monaca plugin rm cordova-plugin-camera`

Please let me know if there are other cases to cover.

**Comment by knight9999** [comment]
Thanks! We will check it.

**Comment by knight9999** [comment]
In Mac or Linux environment, we want to use following file path structure.
```
$ monaca plugin add /Users/knaito/mydir/myplugin
$ monaca plugin add ~/../../somedir/someplugin
```

So please improve `getInstallType` function and `isFile` function to identify as
1. If the string in which the first letter is '/'  is File path.
2. If the string in which the first letter is '~' is File path.

**Comment by knight9999** [comment]
Furthermore in mac or linux environment, if we use
```
$ monaca plugin add file://Users/knaito/mydir/myplugin
```
the `folder` variable becomes `Users/knaito/mydir/myplugin` in `addPlugin` function because of the line
```
folder = pluginArg.replace('file:///', '').replace('file://', '').replace('file:/', '');
```

But this is not good.
In this case, the `folder` variable should be `/Users/knaito/mydir/myplugin`.
Please do not remove the first letter `/` in such case in Mac or Linux environment.

**Comment by magyarbitware** [comment]
> Please do not remove the first letter / in such case in Mac or Linux environment.

@knight9999 Should I check for mac and linux environment only, or should this logic be applied to every system except windows?


System | os.platform()
-- | --
Android | android
Windows/Cygwin | win32
Mac OS X | darwin
FreeBSD | freebsd
OpenBSD | openbsd
IBM AIX | aix
Solaris | sunos
Linux & Others | linux

**Comment by knight9999** [comment]
Thanks @magyarbitware 
Only Checking Mac OS X and Linux (and Windows) is enough.
You need not check other environment.

**Comment by magyarbitware** [comment]
I added the required logic not to loose the / in the beginning of the linux and mac path-s.
Please test on linux and mac environments as I could only test on windows.
Thank you

**Comment by knight9999** [comment]
Sorry for the late reply.
I want to add `add-plugin-command.js` followings,

1. add the new function like

**Comment by knight9999** [comment]
Sorry for the late reply.

Could you please add following validations?

1. If the plugin already exists in the project, `plugin add` command should fail.

2. If the plugin is local file path type, the location of the plugin must be under the project root directory.
If the plugin's location is out of the project root, `plugin add` command should fail.
  [For example] The plugin folder is `project/res/custom_plugins/some_plugin`.

Please ask me any question. Thanks

**Comment by magyarbitware** [comment]
I added the validations as requested. Please test also on linux and mac. Thank you

**Review by knight9999 — APPROVED** [review]
To marge this to `dev_plugin_add_command` instead of master.

**Pull request merged**
