### PR TITLE
add no browser open option at preview

### PR DESCRIPTION
**Pull request by mk2**
Opening browser at every preview command makes me bothering, so add no browser open option.

### CODE REVIEW

**Comment by mk2** [comment]
Anyone treats my pull-request, please...

**Comment by andipavllo** [comment]
@mk2 thank you for your pull request, we will review it soon

**Comment by frandiox** [comment]
@mk2 Thanks! This will be merged in #56

**Comment by mk2** [comment]
Thanks! @frankdiox @andipavllo

**Pull request closed without merging**
